### ISSUE TITLE
设备发现模块存在错误

### ISSUE THREAD

**Issue by Dynesshely** [Crequency/KitX-Mobile#9]
**📄 Describe the bug**
未能够正确发现本机以及局域网中的其它设备

**⛏ To Reproduce**
...

**⚒ Expected behavior**
正确显示本机以及局域网中的其他设备

**🖼 Screenshots**
![image](https://user-images.githubusercontent.com/50760269/208112929-cdd8bdcb-8c77-4cda-bd91-f63d919dbd8a.png)

**🖥 Desktop (please complete the following information):**
...

**📱 Smartphone (please complete the following information):**
...

**📎 Additional context**
断开 Wifi 连接并取消保存, 重新连接 Wifi, 再重启 KitX 恢复正常
根据日志推测, IPv6 获取失败导致了异常

**Comment by Cronyet** [comment]
这个应该早就修好了吧 (

**Comment by LYF511** [comment]
这个貌似属于系统级缺陷。。。等再出问题的时候再说吧
